export const WS_EVENTS = {
  // Server → Client
  SLOT_DETECTED: 'SLOT_DETECTED',
  BOOKING_SUCCESS: 'BOOKING_SUCCESS',
  BOOKING_FAILED: 'BOOKING_FAILED',
  BOOKING_PROGRESS: 'BOOKING_PROGRESS',
  CAPTCHA_REQUIRED: 'CAPTCHA_REQUIRED',
  CAPTCHA_MANUAL_NEEDED: 'CAPTCHA_MANUAL_NEEDED',
  COOKIE_EXPIRING_SOON: 'COOKIE_EXPIRING_SOON',
  MONITOR_CRASHED: 'MONITOR_CRASHED',
  MONITOR_DEAD: 'MONITOR_DEAD',
  LOG_ENTRY: 'LOG_ENTRY',
  MONITOR_STATUS: 'MONITOR_STATUS',
  BATCH_PROGRESS: 'BATCH_PROGRESS',

  // Client → Server
  CAPTCHA_SOLVED: 'CAPTCHA_SOLVED',
} as const;
